// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1633535042);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1633534802);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1633534922);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1633534832);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1633535162);
user_pref("browser.cache.disk.amount_written", 111);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1633535043);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"0a2a1127-ac2c-4ae2-b980-c0820a4b68eb\"}");
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "0b69ca5d-51e5-4ecf-9e38-cab6e1a9a7f");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("security.sandbox.plugin.tempDirSuffix", "3b78f02b-33fd-404f-9db9-0d731513fb1e");
user_pref("services.settings.clock_skew_seconds", -1344);
user_pref("services.settings.last_etag", "\"1633529266296\"");
user_pref("services.settings.last_update_seconds", 1633536266);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1633536266);
user_pref("services.settings.main.hijack-blocklists.last_check", 1633536266);
user_pref("services.settings.main.language-dictionaries.last_check", 1633536266);
user_pref("services.settings.main.search-config.last_check", 1633536266);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1633536266);
user_pref("services.settings.main.sites-classification.last_check", 1633536266);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1633536266);
user_pref("toolkit.telemetry.cachedClientID", "fe06e65a-8247-4c78-8e07-6906ea660227");
user_pref("toolkit.telemetry.previousBuildID", "20210802223056");
